#!/usr/bin/env python
# -*- coding: utf-8 -*-
#AUTOGENERATED FILE

from cheese.databaseControll.database import Database

class PasswordRepositoryImpl:

    @staticmethod
    def init():
        PasswordRepositoryImpl.table = "passwords"
        PasswordRepositoryImpl.scheme = "(id,user_id,password,duration)"
        PasswordRepositoryImpl.schemeNoBrackets = "id,user_id,password,duration"

    @staticmethod
    def findValidPassword(args):
        userId = args[0]

        response = Database.query(f"select case when exists         (select * from passwords p where p.user_id = {userId})         then cast(1 as bit)         else cast(0 as bit) end;")
        Database.done()
        if (response[0][0] == "1"): return True
        return False

    @staticmethod
    def findNewId(args):

        response = Database.query(f"select count(*) from passwords;")
        Database.done()
        return int(response[0][0])

    @staticmethod
    def save(args):
        obj = args[0]

        try:
            Database.commit(f"insert into {PasswordRepositoryImpl.table} {PasswordRepositoryImpl.scheme} values {obj};")
            Database.done()
            return True
        except Exception as e:
            print(e)
            return False

    @staticmethod
    def update(args):
        obj = args[0]

        try:
            Database.commit(f"update {PasswordRepositoryImpl.table} set {PasswordRepositoryImpl.scheme} = {obj} where id={obj[0]};")
            Database.done()
            return True
        except Exception as e:
            print(e)
            return False

    @staticmethod
    def toJson(object):
        scheme = PasswordRepositoryImpl.schemeNoBrackets.split(",")
        ret = {}
        for s, o in zip(scheme, list(object)):
            try:
                ret[s] = int(o)
            except:
                ret[s] = o
        return ret

