#!/usr/bin/env python
# -*- coding: utf-8 -*-

import psycopg2

from cheese.appSettings import Settings

"""
File generated by Cheese Framework

database connection of Cheese Application
"""

class Database:

    # connect to database
    @staticmethod
    def connect():
        Database.connection = psycopg2.connect(
                host=Settings.dbHost,
                database=Settings.dbName,
                user=Settings.dbUser,
                password=Settings.dbPassword,
                port=Settings.dbPort)

        Database.cursor = Database.connection.cursor()
        print(f"CONNECTED TO {Settings.dbHost}:{Settings.dbPort} {Settings.dbName}")

    # close connection with database
    @staticmethod
    def close():
        Database.cursor.close()
        print(f"CONNECTION TO {Settings.dbHost}:{Settings.dbPort} {Settings.dbName} CLOSED")

    # select query
    @staticmethod
    def query(sql):
        print("QUERY: " + sql)
        Database.cursor.execute(sql)
        return Database.cursor.fetchall()

    # insert, update ...
    @staticmethod
    def commit(sql):
        print("COMMIT: " + sql)
        Database.cursor.execute(sql)

    # commit when done
    @staticmethod
    def done():
        Database.connection.commit()