#!/usr/bin/env python
# -*- coding: utf-8 -*-

import psycopg2

from cheese.appSettings import Settings
from cheese.Logger import Logger

"""
File generated by Cheese Framework

database connection of Cheese Application fro PostgreSQL
"""

class PostgreDB:

    # connect to database
    def connect(self):
        self.connection = psycopg2.connect(
                host=Settings.dbHost,
                database=Settings.dbName,
                user=Settings.dbUser,
                password=Settings.dbPassword,
                port=Settings.dbPort)

        self.cursor = self.connection.cursor()
        Logger.okBlue(f"CONNECTED TO {Settings.dbHost}:{Settings.dbPort} {Settings.dbName}")

    # close connection with database
    def close(self):
        self.cursor.close()
        Logger.okBlue(f"CONNECTION TO {Settings.dbHost}:{Settings.dbPort} {Settings.dbName} CLOSED")

    # select query
    def query(self, sql):
        self.cursor = self.connection.cursor()
        Logger.okBlue(Logger.WARNING + "QUERY: " + Logger.ENDC + sql)
        try:
            self.cursor.execute(sql)
        except:
            self.rollback()
            return None
        ret = self.cursor.fetchall()
        self.cursor.close()
        return ret

    # insert, update ...
    def commit(self, sql):
        if (Settings.allowCommit):
            self.cursor = self.connection.cursor()
            Logger.okBlue(Logger.WARNING + "COMMIT: " + Logger.ENDC + sql)
            try:
                self.cursor.execute(sql)
            except:
                self.rollback()
            self.cursor.close()
        else:
            Logger.fail("Commiting is not allowed")

    # commit when done
    def done(self):
        self.connection.commit()

    def rollback(self):
        self.connection.rollback()