#!/usr/bin/env python
# -*- coding: utf-8 -*-

from http.server import BaseHTTPRequestHandler

from cheese.modules.cheeseController import CheeseController
from python.authorization import Authorization

#REST CONTROLLERS


"""
File generated by Cheese Framework

server handler of Cheese Application
"""

class CheeseServer(BaseHTTPRequestHandler):
    def do_GET(self):
        if (self.path == "/"):
            CheeseController.sendFile(self, "index.html")
        else:
            CheeseController.sendFile(self, self.path)

        pass

    def do_POST(self):

        pass