#!/usr/bin/env python
# -*- coding: utf-8 -*-

from http.server import BaseHTTPRequestHandler

from cheese.modules.cheeseController import CheeseController
from python.authorization import Authorization

#REST CONTROLLERS
from python.controllers.authenticationController import AuthenticationController
from python.controllers.chatController import ChatController
from python.controllers.messageController import MessageController
from python.controllers.userController import UserController


"""
File generated by Cheese Framework

server handler of Cheese Application
"""

class CheeseServer(BaseHTTPRequestHandler):
    def do_GET(self):
        path = CheeseController.getPath(self.path)
        auth = Authorization.authorize(self, path, "GET")

        if (path == "/"):
            CheeseController.serveFile(self, "index.html")
        elif (path.startswith("/authentication")):
            pass
        elif (path.startswith("/chats")):
            pass
        elif (path.startswith("/messages")):
            pass
        elif (path.startswith("/users")):
            pass
        else:
            CheeseController.serveFile(self, self.path)

        pass

    def do_POST(self):
        auth = Authorization.authorize(self, self.path, "POST")

        if (self.path.startswith("/authentication")):
            if (self.path == "/authentication/login"):
                AuthenticationController.login(self, self.path, auth)
            elif (self.path == "/authentication/getUserByToken"):
                AuthenticationController.getUserByToken(self, self.path, auth)
            else:
                CheeseController.sendResponse(self, b"Endpoint not found :(", 404)
        elif (self.path.startswith("/chats")):
            if (self.path == "/chats/getChats"):
                ChatController.getChats(self, self.path, auth)
            elif (self.path == "/chats/getChatsById"):
                ChatController.getChatsById(self, self.path, auth)
            elif (self.path == "/chats/createChat"):
                ChatController.createChat(self, self.path, auth)
            else:
                CheeseController.sendResponse(self, b"Endpoint not found :(", 404)
        elif (self.path.startswith("/messages")):
            if (self.path == "/messages/getChatMessages"):
                MessageController.getChatMessages(self, self.path, auth)
            elif (self.path == "/messages/sendMessage"):
                MessageController.sendMessage(self, self.path, auth)
            elif (self.path == "/messages/seenMessage"):
                MessageController.seenMessage(self, self.path, auth)
            else:
                CheeseController.sendResponse(self, b"Endpoint not found :(", 404)
        elif (self.path.startswith("/users")):
            if (self.path == "/users/createUser"):
                UserController.createUser(self, self.path, auth)
            elif (self.path == "/users/getUser"):
                UserController.getUser(self, self.path, auth)
            elif (self.path == "/users/getUserByName"):
                UserController.getUserByName(self, self.path, auth)
            elif (self.path == "/users/update"):
                UserController.update(self, self.path, auth)
            elif (self.path == "/users/getUserDynamic"):
                UserController.getUserDynamic(self, self.path, auth)
            else:
                CheeseController.sendResponse(self, b"Endpoint not found :(", 404)
        else:
            CheeseController.sendResponse(self, b"Endpoint not found :(", 404)

        pass