#!/usr/bin/env python
# -*- coding: utf-8 -*-

import json

from cheese.resourceManager import ResMan

"""
File generated by Cheese Framework

class that stores Cheese Application settings
"""

class Settings:

    # load settings
    @staticmethod 
    def loadSettings():
        with open(f"{ResMan.root()}/appSettings.json", "r") as f:
            settings = json.loads(f.read())
            Settings.host = settings["host"]
            Settings.port = settings["port"]
            Settings.dbDriver = settings["dbDriver"]
            Settings.dbHost = settings["dbHost"]
            Settings.dbName = settings["dbName"]
            Settings.dbUser = settings["dbUser"]
            Settings.dbPassword = settings["dbPassword"]
            Settings.dbPort = settings["dbPort"]
            Settings.allowCommit = settings["allowCommit"]
            Settings.allowMultiThreading = settings["allowMultiThreading"]
            Settings.allowCORS = settings["allowCORS"]
            Settings.allowDB = settings["allowDB"]