#!/usr/bin/env python
# -*- coding: utf-8 -*-

import json

from cheese.resourceManager import ResMan

"""
File generated by Cheese Framework

class that stores Cheese Application settings
"""

class Settings:

    settings = {}

    # load settings
    @staticmethod 
    def loadSettings():
        with open(f"{ResMan.root()}/appSettings.json", "r") as f:
            Settings.settings = json.loads(f.read())
            Settings.host = Settings.settings["host"]
            Settings.port = Settings.settings["port"]
            Settings.dbDriver = Settings.settings["dbDriver"]
            Settings.dbHost = Settings.settings["dbHost"]
            Settings.dbName = Settings.settings["dbName"]
            Settings.dbUser = Settings.settings["dbUser"]
            Settings.dbPassword = Settings.settings["dbPassword"]
            Settings.dbPort = Settings.settings["dbPort"]
            Settings.allowDebug = Settings.settings["allowDebug"]
            Settings.allowCommit = Settings.settings["allowCommit"]
            Settings.allowMultiThreading = Settings.settings["allowMultiThreading"]
            Settings.allowCORS = Settings.settings["allowCORS"]
            Settings.allowDB = Settings.settings["allowDB"]
            Settings.allowLogReader = Settings.settings["allowLogReader"]