#!/usr/bin/env python
# -*- coding: utf-8 -*-

from cheese.resourceManager import ResMan

#REST CONTROLLERS
from python.controllers.authenticationController import AuthenticationController
from python.controllers.chatController import ChatController
from python.controllers.messageController import MessageController
from python.controllers.userController import UserController


"""
File generated by Cheese Framework

REST controller manager of Cheese Application
"""

class ControllerManager:

    @staticmethod
    def initControllers():
        AuthenticationController.init()
        ChatController.init()
        MessageController.init()
        UserController.init()

        pass