#!/usr/bin/env python
# -*- coding: utf-8 -*-

import inspect

from cheese.resourceManager import ResMan
from cheese.databaseControll.database import Database

#REPOSITORIES


"""
File generated by Cheese Framework

Database query of Cheese Application
"""

class CheeseRepository:





    @staticmethod
    def initRepositories():

        pass

    # finds name of user-made repository
    @staticmethod
    def findUserRepository():
        curframe = inspect.currentframe()
        calframe = inspect.getouterframes(curframe, 2)
        userRepository = ResMan.getFileName(calframe[2][1]).replace(".py", "")
        return userRepository

    @staticmethod
    def save(a):
        print(a)

    @staticmethod 
    def saveTemp(table, object):
        Database.commit(f"{table}")
