#!/usr/bin/env python
# -*- coding: utf-8 -*-

from urllib.parse import unquote
import os

from cheese.resourceManager import ResMan

"""
File generated by Cheese Framework

REST controller of Cheese Application
"""

class CheeseController:
    
    #send file
    @staticmethod
    def sendFile(server, file, header="text/html"):
        file = unquote(file)
        file = ResMan.joinPath(ResMan.web(), file)

        print(f"Serving file: {file}")
        
        if (not os.path.exists(f"{file}")):
            with open(f"{ResMan.error()}/error404.html", "rb") as f:
                CheeseController.sendResponse(server, f.read(), 404)
            return

        with open(f"{file}", "rb") as f:
            CheeseController.sendResponse(server, f.read(), 200, header)

    # sends response
    @staticmethod
    def sendResponse(server, content, errorCode, contentType="text/html"):
        server.send_response(errorCode)
        server.send_header("Content-type", contentType)
        server.end_headers()

        server.wfile.write(content)
