#!/usr/bin/env python
# -*- coding: utf-8 -*-

import requests
import time

from cheese.cheese import Cheese
from cheese.appSettings import Settings

"""
File generated by Cheese Framework

main file of Cheese Application
"""


if __name__ == "__main__":
    Cheese.init()

    time.sleep(1)
    requests.get(f"http://localhost/services/doYouKnowMe?name=Frogie&port={Settings.port}&icon=android-chrome-192x192.png")

    Cheese.serveForever()

    