#!/usr/bin/env python
# -*- coding: utf-8 -*-

from cheese.cheese import Cheese

"""
File generated by Cheese Framework

main file of Cheese Application
"""


if __name__ == "__main__":
    Cheese.init()

    Cheese.serveForever()

    